### ISSUE TITLE
phone number is not getting saved

### ISSUE THREAD

**Issue by ajithfort** [udokmeci/yii2-phone-validator#1]
hi,

my model code

 [['phone_number'], 'udokmeci\yii2PhoneValidator\PhoneValidator','country'=>'IN'],

data i entered is 9809****30 (10 digit valid Indian phone number) the data which is getting stored in db is 91 which is our country code.

**Comment by udokmeci** [comment]
Hi,
As you said I tried it on https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html since it uses the same library. 
It has to return +91 98091 23430 for such a number. Maybe the phone column in database allow 3 chars? I don't know. But more debugging would help to understand what is wrong here.

**Comment by ajithfort** [comment]
there is only 2 rules for phone_number
[['phone_number'], 'integer'],
[['phone_number'], 'udokmeci\yii2PhoneValidator\PhoneValidator','country'=>'IN'],
in DB its int(15)

**Comment by udokmeci** [comment]
Hi,
Since it is not an integer as you can see it is a string. So it take the integer part of +91 98091 23430 which is +91 -> 91.
Change it to varchar or something.

**Comment by udokmeci** [comment]
Ah so, you made it. OK. Good luck
